#!/bin/bash

pushd .

fis3  > /dev/null 2>&1  || source .node6
cd ~/src/vis4/apps0
rm -fr /Users/is/src/tmp/makenv.github.io/is/demos/vis4/*
fis3 release github \
  -d /Users/is/src/tmp/makenv.github.io/is/demos/vis4/ \
  --verbose --clean

cd /Users/is/src/tmp/makenv.github.io/is/demos/vis4/

git add .
git commit -m "update vis4 $(date +'%Y-%m-%d %H:%M:%S')"
git push

popd