#!/bin/bash


pushd .
cd ~/src/vis4/apps0
rm -fr /Users/is/src/tmp/makenv.github.io/is/demos/vis4/*
fis3 release github -d ../dist-0 --verbose --clean
cd /Users/is/src/tmp/makenv.github.io/is/demos/vis4/
git add .
git commit -m 'update vis4'
git push
popd